if (process.env.USER) require("dotenv").config();
const express = require("express");
const cors = require("cors");
const errorHandler = require("./errors/errorHandler");
const moviesRouter = require("./movies/moviesRouter.js");
const theatersRouter = require("./theaters/theatersRouter");
const reviewsRouter = require("./reviews/reviewsRouter");
const notFound = require("./errors/notFound.js");
const methodNotAllowed = require("./errors/methodNotAllowed");
const app = express();
app.use(cors());
app.use(express.json());
app.use("/movies", moviesRouter);
app.use("/theaters", theatersRouter);
app.use("/reviews", reviewsRouter);
app.use(methodNotAllowed);
app.use(notFound);
app.use(errorHandler);
module.exports = app;
